=== GiselleFT/ProyectoKinder/proyectoKinder/web/esquemaUsuario.xsd
<!--
    ********USUARIO********
    *tipo = Se refiere al tipo de usuario.
            -Administrador 1
            -Profesor 2
            -Alumno 3
            
    *nombre = Cadena que contiene el Nombre del usuario. Conformado por:
              Nombre, Apellido Paterno, Apellido Materno
    
    *usuario = Cadena que contiene el Nombre para identificarlo como usuario
    
    *contrasena = Cadena que contiene la constraseÃ±a que crea el usuario al registrarse
             
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="raiz">   
        <xs:element name="USUARIO">
            <xs:complexType>
                <xs:all>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="usuario" type="xs:string"/>
                    <xs:element name="contrasena" type="xs:string"/>
                </xs:all>
                <xs:attribute name="id" use="required"/>
                <xs:attribute name="tipo" use="required"/>
            </xs:complexType>
        </xs:element>
    </xs:element>
</xs:schema>

=== GiselleFT/ProyectoKinder/proyectoKinder/web/BD.xml
<?xml version="1.0" encoding="UTF-8"?>
<raiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="esquemaUsuario.xsd">
  <USUARIO id="1" tipo="1">
    <nombre>root</nombre>
    <usuario>root</usuario>
    <contrasena>root</contrasena>
  </USUARIO>
  <USUARIO id="2" tipo="2">
    <nombre>profesor</nombre>
    <usuario>profesor</usuario>
    <contrasena>profesor</contrasena>
  </USUARIO>
  <USUARIO id="3" tipo="3">
    <nombre>alumno</nombre>
    <usuario>alumno</usuario>
    <contrasena>alumno</contrasena>
  </USUARIO>
</raiz>
